version: '3'

services:

  anaconda:
    image: continuumio/anaconda3
    volumes:
       - ./:/opt/notebooks
    ports:
      - "8888:8888"
    command:
      /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    tty: true
  
  mssql:
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment:
     - SA_PASSWORD=GB760gb760!
     - ACCEPT_EULA=Y
     - MSSQL_PID=Developer
     - hostname=mssql
   ports:
     - "1433:1433"
   container_name: mssql

  #sqlpad:
  # To use Dockerfile at root of this project, use build instead of image
  # build: ../../
    #image: sqlpad/sqlpad:latest
    #hostname: 'sqlpad'
    #name: 'sqlpad' 
    #container_name: 'sqlpad'
    #ports:
    #  - '3000:3000'
    #environment:
    #  SQLPAD_ADMIN: 'admin'
    #  SQLPAD_ADMIN_PASSWORD: 'password'
    #  SQLPAD_APP_LOG_LEVEL: info
    #  SQLPAD_WEB_LOG_LEVEL: warn
    #  SQLPAD_CONNECTIONS__sqlserverdemo__name: SQL Server Demo
    #  SQLPAD_CONNECTIONS__sqlserverdemo__driver: sqlserver
    #  SQLPAD_CONNECTIONS__sqlserverdemo__host: mssql
    #  SQLPAD_CONNECTIONS__sqlserverdemo__database: master
    #  SQLPAD_CONNECTIONS__sqlserverdemo__username: sa
    #  SQLPAD_CONNECTIONS__sqlserverdemo__password: GB760gb760!
    #volumes:
    #  - '/mnt/d/src/lab/sqlpad/data:/var/lib/sqlpad'
      #- '~/sqlpad/data:/var/lib/sqlpad'

  #sqlite3:
  # image: nouchka/sqlite3:latest
  # stdin_open: true
  # tty: true
  # volumes:
  #   - ./db/:/root/db/

  #sqlitebrowser:
  # image: lscr.io/linuxserver/sqlitebrowser:latest
  # container_name: sqlitebrowser
  # environment:
  #   - PUID=1000
  #   - PGID=1000
  #   - TZ=Europe/London
  # volumes:
  #   - .:/config
  # ports:
  #   - 4000:3000
  # restart: unless-stopped
  #cloudbeaver:
  #  image: dbeaver/cloudbeaver:latest
  #  container_name: cloudbeaver
  #  restart: unless-stopped
  #  ports:
  #    - "8200:8978"
  #  volumes:
  #    - ./workspace:/opt/cloudbeaver/workspace